# Site settings
author: Hillevi
title: Hillevi's Blog
header-img: img/home-bg.png
email: hillevieklow@gmail.com
copyright_name: Hillevi
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: hillevieklow
github_username:  hillevieklow

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
